wandb_version: 1

activation:
  desc: null
  value: linear
activation_layers:
  desc: null
  value: !!python/object:tensorflow.python.keras.layers.advanced_activations.LeakyReLU
    _activity_regularizer: null
    _call_convention: !!python/object/apply:tensorflow.python.keras.engine.base_layer_utils.CallConvention
    - 1
    _call_fn_args: !!python/tuple
    - inputs
    _call_is_graph_friendly: true
    _callable_losses: []
    _compute_previous_mask: true
    _dtype: null
    _eager_losses: []
    _expects_training_arg: false
    _inbound_nodes: []
    _initial_weights: null
    _layers: []
    _losses: []
    _metrics: []
    _metrics_tensors: {}
    _name: leaky_re_lu
    _non_trainable_weights: []
    _outbound_nodes: []
    _setattr_tracking: true
    _trainable_weights: []
    _updates: []
    alpha: !!python/object/apply:numpy.core.multiarray._reconstruct
      args:
      - !!python/name:numpy.ndarray ''
      - !!python/tuple
        - 0
      - !!binary |
        Yg==
      state: !!python/tuple
      - 1
      - !!python/tuple []
      - !!python/object/apply:numpy.dtype
        args:
        - f4
        - 0
        - 1
        state: !!python/tuple
        - 3
        - <
        - null
        - null
        - null
        - -1
        - -1
        - 0
      - false
      - !!binary |
        AABAQA==
    built: false
    input_spec: null
    stateful: false
    supports_masking: true
    trainable: true
dense_layer_size:
  desc: null
  value: 128
dropout:
  desc: null
  value: 0.2
epochs:
  desc: null
  value: 10
first_layer_conv_height:
  desc: null
  value: 3
first_layer_conv_width:
  desc: null
  value: 3
first_layer_convs:
  desc: null
  value: 32
img_height:
  desc: null
  value: 28
img_width:
  desc: null
  value: 28
